[package]
name = "quad-tree-host"
version = "0.1.0"
edition = "2021"

[dependencies]
pico-sdk = { workspace = true }
quad-tree-core = { path = "../core" }
sha3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
ml-kem = { workspace = true }

[[bin]]
name = "quad-host"
path = "src/main.rs"
