[package]
name = "quad-tree-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
sha3 = { version = "0.10", default-features = false }
